#!/usr/bin/env ruby

require 'pathname'
require 'json'
require 'yaml'

require_relative './helpers.rb'

pull_repos

envs = ALL_ENV_PATHS.map do |path|
  OpsmanEnvFactory.create_env(path)
end

envs.compact.each do |env|
  env.add_to_ssh_config(SSH_CONFIG_PATH)
end

puts "Done."
