#!/usr/bin/env ruby

require 'json'
require 'pathname'
require 'tempfile'
require_relative './helpers.rb'

script_name = "ssh_opsman_bosh"

envs = ALL_ENV_PATHS.map do |path|
  OpsmanEnvFactory.create_env(path)
end.compact

om_env_name = ARGV[0]
fail "Usage: #{script_name} [ops-man-environment-name]" unless om_env_name

om_env = envs.select { |env| env.name == om_env_name }.first
fail "Environment #{om_env_name} not recognised" unless om_env

director_ip = om_env.get_director_ip

`chmod 0400 #{om_env.ssh_key}`
`ssh-add #{om_env.ssh_key}`
`sudo sshuttle -r #{om_env.ssh_user}@#{om_env.ssh_host} "10.0.0.0/8" --daemon`

trap("SIGINT") { `sudo kill $(cat sshuttle.pid)`; exit 0 }

puts ""
puts "> Open a new terminal and run"
puts_blue "ssh vcap@#{director_ip}"
puts ""
puts "> Hit Ctrl-C when done."

sleep
